services:
  - type: web
    name: bondly-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bondly_v1.5.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
